# Site settings
title: Cuterpillar machine
url: "https://cuterpillar-machine.github.io"
baseurl: ""
githuburl: https://github.com/cuterpillar-machine
description: > #
  Cuterpillar machine...
versions_limit: 3

# theme
theme: jekyll-theme-cayman
lang: en-US
site:
  favicon: "/assets/favicon.ico"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Google services
google_analytics: G-68D4G5CNZ4

collections:
  versions:
    output: true
    permalink: /versions/:path.html
future: true
